# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-04 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentBasic', '0002_auto_20161004_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20, verbose_name='公司名')),
                ('address', models.CharField(max_length=20, verbose_name='公司地址')),
                ('date', models.DateField(verbose_name='日期')),
                ('duration', models.DurationField(verbose_name='面试时长')),
                ('problem', models.TextField(verbose_name='遇到的问题')),
                ('reason', models.TextField(verbose_name='失败原因')),
                ('summary', models.TextField(verbose_name='面试总结')),
                ('task', models.TextField(verbose_name='要求')),
                ('task_completion', models.TextField(verbose_name='要求完成情况')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.Student', verbose_name='学生')),
            ],
        ),
    ]
