# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-19 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentBasic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=20, verbose_name='公司名')),
                ('address', models.CharField(blank=True, max_length=20, verbose_name='公司地址')),
                ('date', models.DateField(verbose_name='日期')),
                ('duration', models.DurationField(verbose_name='面试时长')),
                ('summary', models.TextField(verbose_name='面试总结')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '面试',
                'verbose_name_plural': '面试',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100, verbose_name='详情')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interview.Interview')),
            ],
            options={
                'verbose_name': '面试问题',
                'verbose_name_plural': '面试问题',
            },
        ),
    ]
