# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='interview',
            name='problem',
        ),
        migrations.AlterField(
            model_name='interview',
            name='reason',
            field=models.TextField(help_text='1111111', verbose_name='失败原因'),
        ),
        migrations.AddField(
            model_name='problem',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interview.Interview'),
        ),
    ]
