# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-12 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0002_auto_20161011_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100, verbose_name='详情')),
            ],
            options={
                'verbose_name_plural': '面试问题',
                'verbose_name': '面试问题',
            },
        ),
        migrations.RemoveField(
            model_name='problem',
            name='interview',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='task',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='task_completion',
        ),
        migrations.AlterField(
            model_name='interview',
            name='address',
            field=models.CharField(blank=True, max_length=20, verbose_name='公司地址'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='company_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='公司名'),
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.AddField(
            model_name='question',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interview.Interview'),
        ),
    ]
