# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-04 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentBasic', '0002_auto_20161004_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(verbose_name='访谈时间')),
                ('operator', models.CharField(choices=[('YinSJ', '尹胜杰'), ('GuoQH', '郭巧会'), ('JinNa', '金娜')], max_length=10, verbose_name='访谈人')),
                ('deportment', models.PositiveIntegerField(verbose_name='仪态')),
                ('expression', models.PositiveIntegerField(verbose_name='表达')),
                ('resume', models.PositiveIntegerField(verbose_name='简历')),
                ('background', models.PositiveIntegerField(verbose_name='背景')),
                ('project', models.PositiveIntegerField(verbose_name='项目')),
                ('skill_point', models.PositiveIntegerField(verbose_name='技能')),
                ('mentality', models.PositiveIntegerField(verbose_name='心态')),
                ('problem', models.TextField(verbose_name='存在的问题')),
                ('task', models.TextField(verbose_name='要求')),
                ('task_completion', models.TextField(verbose_name='完成情况')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name_plural': '访谈',
                'verbose_name': '访谈',
            },
        ),
    ]
