# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='time',
            field=models.DateTimeField(verbose_name='访谈时间'),
        ),
    ]
