# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-12 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0002_auto_20161011_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
