# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-12 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0003_auto_20161012_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('deportment', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='哈哈，SB', verbose_name='仪态')),
                ('proble', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='background',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='deportment',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='expression',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='mentality',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='skill_point',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='time',
            field=models.DateTimeField(verbose_name='访谈时间'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='deportmentScore',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Conversation.stuScore'),
        ),
    ]
