# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0004_auto_20161012_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='deportmentScore',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='stuscore',
            name='deportment',
        ),
        migrations.RemoveField(
            model_name='stuscore',
            name='proble',
        ),
        migrations.AddField(
            model_name='conversation',
            name='background_problem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='background_score',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='背景'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='deportment_problem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='deportment_score',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='哈哈，SB', verbose_name='仪态'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='expression_problem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='expression_score',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='表达'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='mentality_problem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='mentality_score',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='心态'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='project_problem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='project_score',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='resume_problem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='resume_score',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='简历'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='skill_point_problem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='skill_point_score',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='技能'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='task_completion',
            field=models.TextField(null=True, verbose_name='完成情况'),
        ),
    ]
