# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-12 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conversation', '0005_auto_20161012_0637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stuScore',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='background_problem',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='存在的问题'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='deportment_problem',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='存在的问题'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='expression_problem',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='存在的问题'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='mentality_problem',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='存在的问题'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='project_problem',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='存在的问题'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='resume_problem',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='存在的问题'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='skill_point_problem',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='存在的问题'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='task_completion',
            field=models.TextField(blank=True, default='', verbose_name='评语'),
        ),
    ]
