# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-19 06:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('entry_time', models.DateField(null=True, verbose_name='入职日期')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('education', models.CharField(choices=[('junior', '初中及以下,我的爷啊'), ('high', '高中'), ('secondary', '中专'), ('college', '大专'), ('university', '本科'), ('master', '硕士及以上，我的哥啊')], max_length=10, verbose_name='学历')),
                ('graduated_school', models.CharField(max_length=20, null=True, verbose_name='毕业学校')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目经理信息',
                'verbose_name_plural': '项目经理信息',
            },
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='班级名')),
                ('product', models.CharField(choices=[('iOS', 'iOS'), ('PHP', 'PHP'), ('Java', 'Java')], max_length=4, verbose_name='产品线')),
                ('graduated_date', models.DateField(verbose_name='结课时间')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.Assistant', verbose_name='项目经理')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
            },
        ),
        migrations.CreateModel(
            name='HeadTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('entry_time', models.DateField(null=True, verbose_name='入职日期')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '班主任',
                'verbose_name_plural': '班主任',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('education', models.CharField(choices=[('junior', '初中及以下,我的爷啊'), ('high', '高中'), ('secondary', '中专'), ('college', '大专'), ('university', '本科'), ('master', '硕士及以上，我的哥啊')], max_length=10, verbose_name='学历')),
                ('graduated_school', models.CharField(max_length=20, null=True, verbose_name='毕业学校')),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.ClassInfo', verbose_name='班级')),
            ],
            options={
                'verbose_name': '学员信息',
                'verbose_name_plural': '学员信息',
            },
        ),
        migrations.AddField(
            model_name='classinfo',
            name='head_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.HeadTeacher', verbose_name='班主任'),
        ),
    ]
