# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 01:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('entry_time', models.DateField(null=True, verbose_name='入职日期')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('education', models.CharField(choices=[('junior', '初中及以下'), ('high', '高中'), ('secondary', '中专'), ('college', '大专'), ('university', '本科'), ('master', '硕士及以上')], max_length=10, verbose_name='学历')),
                ('graduated_school', models.CharField(max_length=20, null=True, verbose_name='毕业学校')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '项目经理信息',
                'verbose_name': '项目经理信息',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='市')),
            ],
            options={
                'verbose_name_plural': '市',
                'verbose_name': '市',
            },
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='班级名')),
                ('product', models.CharField(choices=[('iOS', 'iOS'), ('PHP', 'PHP'), ('Java', 'Java')], max_length=4, null=True, verbose_name='产品线')),
                ('graduated_date', models.DateField(null=True, verbose_name='结课时间')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.Assistant', verbose_name='项目经理')),
            ],
            options={
                'verbose_name_plural': '班级信息',
                'verbose_name': '班级信息',
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='省')),
            ],
        ),
        migrations.CreateModel(
            name='HeadTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('entry_time', models.DateField(null=True, verbose_name='入职日期')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '班主任',
                'verbose_name': '班主任',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, null=True, verbose_name='性别')),
                ('id_number', models.CharField(max_length=18, null=True, validators=[django.core.validators.RegexValidator(message='请输入正确的身份证号', regex='^\\d{17}[\\d,x,X]')], verbose_name='身份证号')),
                ('phone_number', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='请输入正确的手机号', regex='^\\d{11}')], verbose_name='手机号')),
                ('qq_number', models.CharField(max_length=20, null=True, verbose_name='QQ号')),
                ('contact', models.CharField(max_length=10, null=True, verbose_name='紧急联系人')),
                ('contact_phone', models.CharField(max_length=20, null=True, verbose_name='紧急联系人手机号')),
                ('graduated_school', models.CharField(max_length=20, null=True, verbose_name='毕业学校')),
                ('education', models.CharField(choices=[('junior', '初中及以下'), ('high', '高中'), ('secondary', '中专'), ('college', '大专'), ('university', '本科'), ('master', '硕士及以上')], max_length=10, null=True, verbose_name='学历')),
                ('education_type', models.CharField(choices=[('1', '全日制统招'), ('2', '函授'), ('3', '自考'), ('4', '其他')], max_length=1, null=True, verbose_name='学历性质')),
                ('cet_level', models.CharField(choices=[('1', '英语四级'), ('2', '英语六级'), ('3', '其他'), ('4', '无')], max_length=1, null=True, verbose_name='英语四六级')),
                ('discipline', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('graduated_date', models.DateField(help_text='格式如2015-09-01', null=True, verbose_name='毕业时间')),
                ('registration_center', models.CharField(choices=[('szlg', '深圳龙岗中心'), ('szba', '深圳宝安中心'), ('szbt', '深圳宝体中心'), ('szkjy', '深圳科技园中心'), ('szlh', '深圳罗湖中心'), ('szdw', '深圳地王中心'), ('szsd', '深圳深大中心'), ('szlhua', '深圳龙华中心')], max_length=10, null=True, verbose_name='报名中心')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='continent', chained_model_field='continent', on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.City')),
                ('class_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.ClassInfo', verbose_name='班级')),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.Continent', verbose_name='省')),
            ],
            options={
                'verbose_name_plural': '学员信息',
                'verbose_name': '学员信息',
            },
        ),
        migrations.AddField(
            model_name='classinfo',
            name='head_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.HeadTeacher', verbose_name='班主任'),
        ),
        migrations.AddField(
            model_name='city',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.Continent'),
        ),
    ]
