# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-04 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('product', models.CharField(choices=[('iOS', 'iOS'), ('PHP', 'PHP'), ('Java', 'Java')], max_length=3)),
                ('assistant', models.CharField(choices=[('LiuHJ', '刘海军'), ('WuJB', '吴锦标'), ('LiWei', '李威'), ('QingTing', '覃挺'), ('YeYH', '叶阳浩'), ('ZhongJY', '钟检英'), ('LiGL', '李广龙'), ('HeSQ', '何双全'), ('GanYM', '甘永明'), ('LuCF', '卢超凡')], max_length=10)),
                ('head_teacher', models.CharField(choices=[('TanLQ', '谭丽琼'), ('ZhongQi', '钟琪'), ('ZhaoPeng', '赵鹏')], max_length=10)),
                ('graduated_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('graduated_school', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
                ('education', models.CharField(choices=[('junior', '初中及以下,我的爷啊'), ('high', '高中'), ('secondary', '中专'), ('college', '大专'), ('university', '本科'), ('master', '硕士及以上，我的哥啊')], max_length=10)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.ClassInfo')),
            ],
        ),
    ]
