# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-04 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentBasic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classinfo',
            options={'verbose_name': '班级信息', 'verbose_name_plural': '班级信息'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学员信息', 'verbose_name_plural': '学员信息'},
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='assistant',
            field=models.CharField(choices=[('LiuHJ', '刘海军'), ('WuJB', '吴锦标'), ('LiWei', '李威'), ('QingTing', '覃挺'), ('YeYH', '叶阳浩'), ('ZhongJY', '钟检英'), ('LiGL', '李广龙'), ('HeSQ', '何双全'), ('GanYM', '甘永明'), ('LuCF', '卢超凡')], max_length=10, verbose_name='项目经理'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='graduated_date',
            field=models.DateField(verbose_name='结课时间'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='head_teacher',
            field=models.CharField(choices=[('TanLQ', '谭丽琼'), ('ZhongQi', '钟琪'), ('ZhaoPeng', '赵鹏')], max_length=10, verbose_name='班主任'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='name',
            field=models.CharField(max_length=10, verbose_name='班级名'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='product',
            field=models.CharField(choices=[('iOS', 'iOS'), ('PHP', 'PHP'), ('Java', 'Java')], max_length=3, verbose_name='产品线'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentBasic.ClassInfo', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education',
            field=models.CharField(choices=[('junior', '初中及以下,我的爷啊'), ('high', '高中'), ('secondary', '中专'), ('college', '大专'), ('university', '本科'), ('master', '硕士及以上，我的哥啊')], max_length=10, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduated_school',
            field=models.CharField(max_length=20, null=True, verbose_name='毕业学校'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=10, verbose_name='姓名'),
        ),
    ]
