# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160930140004 on 2016-10-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentBasic', '0002_auto_20161004_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='product',
            field=models.CharField(choices=[('iOS', 'iOS'), ('PHP', 'PHP'), ('Java', 'Java')], max_length=4, verbose_name='产品线'),
        ),
    ]
